# Generated by Django 5.1.1 on 2024-10-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=50)),
                ('home_town', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
