# Generated by Django 5.1.1 on 2024-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeedataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='salary',
            field=models.BigIntegerField(),
        ),
    ]
